#!/bin/sh /etc/rc.common

# Start the tunnel.sh script
START=99
STOP=10

start() {
    /root/tunnel.sh
}

stop() {
    # If you want to stop the tunnel script, you can add kill command here.
    tmux send-keys -t ssh_tunnel C-c
    sleep 2
    tmux kill-session -t ssh_tunnel
    sleep 1
    service redsocks stop
    echo "Stopping tunnel.sh is implemented."
}
