#!/bin/sh /etc/rc.common

# Start the tunnel.sh script
START=99
STOP=10

sleep 25
start() {
    /root/tunnel.sh
    /etc/init.d/passwall start
}

stop() {
    # If you want to stop the tunnel script, you can add kill command here.
    tmux send-keys -t ssh_tunnel C-c
    sleep 1
    tmux kill-session -t ssh_tunnel
}
